version: '3.8'

services:
  discord-notetaker:
    build: .
    container_name: discord-notetaker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - LOG_LEVEL=info
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge

volumes:
  data:
  models: